#!/bin/bash

start() {
cd /opt/apply_for_channel
uwsgi --http :80 --chdir /opt/apply_for_channel --module django_wsgi --daemonize uwsgi.log --pidfile uwsgi.pid
}

stop() {
cd /opt/apply_for_channel
uwsgi --stop uwsgi.pid
/usr/bin/python /opt/apply_for_channel/clean.py
}

restart() {
stop
start
}

reload() {
cd /opt/apply_for_channel
uwsgi --reload uwsgi.pid
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  reload)
    reload
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?